DAILY_SIGNS = [
    {
        "sign_no": 1, "title": "守正签",
        "original_text": "云开未必即见月，先把心灯照一程。",
        "plain_explanation": "事情尚未完全明朗，先把自己的原则、节奏和底线整理清楚。",
        "keywords": ["守正", "清明", "定心"],
        "cultural_source": "易经乾卦：自强不息",
        "inspiration": "今天适合先稳住内在秩序，不急着用外界结果证明自己。",
    },
    {
        "sign_no": 2, "title": "蓄势签",
        "original_text": "春水在冰下，声息未曾停。",
        "plain_explanation": "表面看似停滞，其实力量正在积累。",
        "keywords": ["蓄势", "耐心", "准备"],
        "cultural_source": "易经坤卦：厚德载物",
        "inspiration": "把暂时的慢，当成给根系生长的时间。",
    },
    {
        "sign_no": 3, "title": "明辨签",
        "original_text": "雾里看花花不语，近前一步见分明。",
        "plain_explanation": "困惑不一定来自事情复杂，也可能是距离还不够近。",
        "keywords": ["观察", "明辨", "靠近"],
        "cultural_source": "易经离卦：明以照物",
        "inspiration": "别急着判断，先补足信息。",
    },
    {
        "sign_no": 4, "title": "和合签",
        "original_text": "两木成林，风过有声。",
        "plain_explanation": "关系中的协作比单方面用力更重要。",
        "keywords": ["协作", "沟通", "和合"],
        "cultural_source": "阴阳相济",
        "inspiration": "今天可以把话说得更柔软，把边界说得更清楚。",
    },
    {
        "sign_no": 5, "title": "止语签",
        "original_text": "山前有路，脚下先停。",
        "plain_explanation": "并非所有时刻都适合表达，沉默有时是整理。",
        "keywords": ["止语", "沉淀", "边界"],
        "cultural_source": "易经艮卦：止而后安",
        "inspiration": "少一点即时回应，多一点真正理解。",
    },
    {
        "sign_no": 6, "title": "启程签",
        "original_text": "轻舟初过浅滩，橹声已入晨光。",
        "plain_explanation": "新的开始不必完美，只要方向清楚，就可以先走一步。",
        "keywords": ["开始", "行动", "轻盈"],
        "cultural_source": "易经震卦：动而生机",
        "inspiration": "把目标拆小，今天只完成第一步。",
    },
    {
        "sign_no": 7, "title": "归藏签",
        "original_text": "秋叶归根，来年自有新枝。",
        "plain_explanation": "有些结束不是失去，而是回到更深的整理。",
        "keywords": ["收束", "复盘", "更新"],
        "cultural_source": "五行木气收藏",
        "inspiration": "允许某件事告一段落，给新状态留空间。",
    },
    {
        "sign_no": 8, "title": "听风签",
        "original_text": "竹影摇窗，风来不问出处。",
        "plain_explanation": "外界变化会带来提醒，但不必被每一种声音牵着走。",
        "keywords": ["倾听", "筛选", "松弛"],
        "cultural_source": "巽卦：入而不迫",
        "inspiration": "听见建议，也保留自己的判断。",
    },
    {
        "sign_no": 9, "title": "见微签",
        "original_text": "一叶落庭前，知时不必惊。",
        "plain_explanation": "小信号值得留意，但不用放大成焦虑。",
        "keywords": ["觉察", "节制", "从容"],
        "cultural_source": "节气物候",
        "inspiration": "观察变化，温柔调整。",
    },
    {
        "sign_no": 10, "title": "抱朴签",
        "original_text": "玉不离石，光在未琢时。",
        "plain_explanation": "真实的自己不必过度包装，朴素也有力量。",
        "keywords": ["真实", "自持", "朴素"],
        "cultural_source": "道家抱朴思想",
        "inspiration": "今天试着少迎合一点，多诚实一点。",
    },
    {
        "sign_no": 11, "title": "临水签",
        "original_text": "水到浅处见石，心到静时见己。",
        "plain_explanation": "情绪安静下来后，你会更容易看见真正的问题。",
        "keywords": ["静心", "自省", "澄明"],
        "cultural_source": "五行水：润下而明",
        "inspiration": "先照顾情绪，再处理事情。",
    },
    {
        "sign_no": 12, "title": "乘时签",
        "original_text": "东风不常在，花开须识时。",
        "plain_explanation": "机会需要节奏，太早太晚都可能消耗力气。",
        "keywords": ["时机", "节奏", "顺势"],
        "cultural_source": "易经时位观",
        "inspiration": "确认准备度，再抓住合适的窗口。",
    },
    {
        "sign_no": 13, "title": "承光签",
        "original_text": "灯火分人暖，暗处亦成春。",
        "plain_explanation": "你拥有的善意和能力，也能照亮别人。",
        "keywords": ["善意", "支持", "温暖"],
        "cultural_source": "离火之象",
        "inspiration": "今天可以主动给一个人明确的支持。",
    },
    {
        "sign_no": 14, "title": "定盘签",
        "original_text": "星河虽远，罗盘有针。",
        "plain_explanation": "选择很多时，先找回自己的核心标准。",
        "keywords": ["选择", "标准", "定向"],
        "cultural_source": "北辰意象",
        "inspiration": "列出三个不可妥协的标准，答案会清楚些。",
    },
    {
        "sign_no": 15, "title": "破茧签",
        "original_text": "旧壳微裂，不是损伤，是新生。",
        "plain_explanation": "不适感可能来自成长，而不是失败。",
        "keywords": ["成长", "突破", "新生"],
        "cultural_source": "震木生发",
        "inspiration": "给变化一点信任，也给自己一点缓冲。",
    },
    {
        "sign_no": 16, "title": "观山签",
        "original_text": "山不语而有势，人不争而有光。",
        "plain_explanation": "稳定的力量不总是喧哗，长期主义更能见功夫。",
        "keywords": ["稳定", "长期", "自信"],
        "cultural_source": "艮山之象",
        "inspiration": "少比较，多积累。",
    },
    {
        "sign_no": 17, "title": "润物签",
        "original_text": "细雨入泥，万物不争先。",
        "plain_explanation": "柔和、持续的行动比一次性爆发更可靠。",
        "keywords": ["持续", "滋养", "柔韧"],
        "cultural_source": "坎水润下",
        "inspiration": "选一件小事，坚持做七天。",
    },
    {
        "sign_no": 18, "title": "照影签",
        "original_text": "镜中不是敌，照见未整理的心。",
        "plain_explanation": "你对他人的反应，可能也映出自己的期待。",
        "keywords": ["投射", "理解", "整理"],
        "cultural_source": "阴阳互见",
        "inspiration": "把不舒服写下来，它也许在提醒你的需要。",
    },
    {
        "sign_no": 19, "title": "开卷签",
        "original_text": "书页一开，古意入今日。",
        "plain_explanation": "传统不是遥远的符号，也可以成为当下生活的提醒。",
        "keywords": ["学习", "开阔", "连接"],
        "cultural_source": "国学经典",
        "inspiration": "今天适合学一个新概念，让经验多一层解释。",
    },
    {
        "sign_no": 20, "title": "从容签",
        "original_text": "月行不疾，终能满庭。",
        "plain_explanation": "真正稳定的变化往往不急，但会持续抵达。",
        "keywords": ["从容", "稳定", "信任"],
        "cultural_source": "太阴月象",
        "inspiration": "把急迫感放下一点，给过程以时间。",
    },
]
